Enabling updates for App Services, which breaks the following test:
```
$ acctests azurerm TestAccAzureRMAppService_tagsUpdate
=== RUN   TestAccAzureRMAppService_tagsUpdate
--- FAIL: TestAccAzureRMAppService_tagsUpdate (109.41s)
	testing.go:513: Step 1 error: Check failed: Check 2/4 error: azurerm_app_service.test: Attribute 'tags.%' expected "2", got "1"
FAIL
exit status 1
FAIL	github.com/terraform-providers/terraform-provider-azurerm/azurerm	109.444s
```