Update private_endpoint.html.markdown
I tried to create a private endpoint and get the following message:
Error: Error creating Private Endpoint "xxxxxxxt"  due to missing 'group Id', ensure that the 'subresource_names' type is populated: network.PrivateEndpointsClient#CreateOrUpdate: Failure sending request: StatusCode=400 -- Original Error: Code="MissingParameterOnPrivateLinkServiceConnection" Message="Private link service connection /subscriptions/xxxxxxx/resourceGroups/xxxxxxxxxxxxxxx/providers/Microsoft.Network/privateEndpoints/xxxxxxxxxxxxxxxx/privateLinkServiceConnections/xxxxx-privateserviceconnection is missing required parameter 'group Id'." Details=[]

So the subresource_names parameter should be marked as required instead of optional