Fix typo
This needs to be capitalised otherwise you will get:
Error: expected identity.0.type to be one of [SystemAssigned UserAssigned
SystemAssigned, UserAssigned], got systemAssigned