r/key_vault_key: switching to use a premium sku for the hsm tests
These require it:

> === RUN   TestAccKeyVaultKey_basicRSAHSM
> === PAUSE TestAccKeyVaultKey_basicRSAHSM
> === CONT  TestAccKeyVaultKey_basicRSAHSM
> testing.go:684: Step 0 error: errors during apply:
> Error: Error Creating Key: keyvault.BaseClient#CreateKey: Failure responding to request: StatusCode=403 -- Original Error: autorest/azure: Service returned an error. Status=403 Code="Forbidden" Message="Hardware key operation not allowed on standard vault" InnerError={"code":"HardwareKeysNotSupported"}

> === RUN   TestAccKeyVaultKey_basicECHSM
> === PAUSE TestAccKeyVaultKey_basicECHSM
> === CONT  TestAccKeyVaultKey_basicECHSM
> testing.go:684: Step 0 error: errors during apply:
> Error: Error Creating Key: keyvault.BaseClient#CreateKey: Failure responding to request: StatusCode=403 -- Original Error: autorest/azure: Service returned an error. Status=403 Code="Forbidden" Message="Hardware key operation not allowed on standard vault" InnerError={"code":"HardwareKeysNotSupported"}