r/media_service_account: temporarily removing support for Tags due to an API bug
```
$ acctests-proxy azurerm TestAccAzureRMMediaServicesAccount_basic
=== RUN   TestAccAzureRMMediaServicesAccount_basic
=== PAUSE TestAccAzureRMMediaServicesAccount_basic
=== CONT  TestAccAzureRMMediaServicesAccount_basic
--- FAIL: TestAccAzureRMMediaServicesAccount_basic (128.02s)
    testing.go:538: Step 0 error: After applying this step, the plan was not empty:

        DIFF:

        UPDATE: azurerm_media_services_account.test
          tags.%: "" => "<computed>"

        STATE:

        azurerm_media_services_account.test:
          ID = /subscriptions/00000000-0000-0000-0000-000000000000/resourceGroups/190222174721721594/providers/Microsoft.Media/mediaservices/acctestmsarfshu
          provider = provider.azurerm
          location = westeurope
          name = acctestmsarfshu
          resource_group_name = 190222174721721594
          storage_account.# = 1
          storage_account.318018769.id = /subscriptions/00000000-0000-0000-0000-000000000000/resourceGroups/190222174721721594/providers/Microsoft.Storage/storageAccounts/acctestsa1rfshu
          storage_account.318018769.is_primary = true

          Dependencies:
            azurerm_resource_group.test
            azurerm_storage_account.first
        azurerm_resource_group.test:
          ID = /subscriptions/00000000-0000-0000-0000-000000000000/resourceGroups/190222174721721594
          provider = provider.azurerm
          location = westeurope
          name = 190222174721721594
          tags.% = 0
        azurerm_storage_account.first:
          ID = /subscriptions/00000000-0000-0000-0000-000000000000/resourceGroups/190222174721721594/providers/Microsoft.Storage/storageAccounts/acctestsa1rfshu
          provider = provider.azurerm
          access_tier =
          account_encryption_source = Microsoft.Storage
          account_kind = Storage
          account_replication_type = GRS
          account_tier = Standard
          account_type = Standard_GRS
          enable_blob_encryption = true
          enable_file_encryption = true
          enable_https_traffic_only = false
          identity.# = 0
          location = westeurope
          name = acctestsa1rfshu
          network_rules.# = 0
          primary_access_key = 2De66EJdd5Am14XG8hYjkgpEf8PJLF0QEvY2QOLaaBzHApo32GWGBKrC5zXyQllegPNI5ex17Sgg0BI+jeYrHQ==
          primary_blob_connection_string = DefaultEndpointsProtocol=https;BlobEndpoint=https://acctestsa1rfshu.blob.core.windows.net/;AccountName=acctestsa1rfshu;AccountKey=2De66EJdd5Am14XG8hYjkgpEf8PJLF0QEvY2QOLaaBzHApo32GWGBKrC5zXyQllegPNI5ex17Sgg0BI+jeYrHQ==
          primary_blob_endpoint = https://acctestsa1rfshu.blob.core.windows.net/
          primary_connection_string = DefaultEndpointsProtocol=https;AccountName=acctestsa1rfshu;AccountKey=2De66EJdd5Am14XG8hYjkgpEf8PJLF0QEvY2QOLaaBzHApo32GWGBKrC5zXyQllegPNI5ex17Sgg0BI+jeYrHQ==;EndpointSuffix=core.windows.net
          primary_file_endpoint = https://acctestsa1rfshu.file.core.windows.net/
          primary_location = westeurope
          primary_queue_endpoint = https://acctestsa1rfshu.queue.core.windows.net/
          primary_table_endpoint = https://acctestsa1rfshu.table.core.windows.net/
          resource_group_name = 190222174721721594
          secondary_access_key = cT0gpMIavYw5zuG/DAxyaKHXpTyzglMfvRO0kAQFagWBuZIejsz0j4jZKWW6ct8/IvcMwp5Ers0C2pwJCvdGCw==
          secondary_connection_string = DefaultEndpointsProtocol=https;AccountName=acctestsa1rfshu;AccountKey=cT0gpMIavYw5zuG/DAxyaKHXpTyzglMfvRO0kAQFagWBuZIejsz0j4jZKWW6ct8/IvcMwp5Ers0C2pwJCvdGCw==;EndpointSuffix=core.windows.net
          secondary_location = northeurope
          tags.% = 0

          Dependencies:
            azurerm_resource_group.test
FAIL
FAIL	github.com/terraform-providers/terraform-provider-azurerm/azurerm	128.566s
```