r/PublicIP: Adding an acceptance test to check that the `ip_address` property is set
This currently fails against the `master` branch:

```
$ acctests azurerm TestAccAzureRMPublicIpStatic_basic
=== RUN   TestAccAzureRMPublicIpStatic_basic
--- FAIL: TestAccAzureRMPublicIpStatic_basic (70.86s)
	testing.go:459: Step 0 error: Check failed: Check 2/3 error: azurerm_public_ip.test: Attribute 'ip_address' expected to be set
FAIL
exit status 1
FAIL	github.com/terraform-providers/terraform-provider-azurerm/azurerm	70.886s
```

But will pass once #772 is merged:

```
$ acctests azurerm TestAccAzureRMPublicIpStatic_basic
=== RUN   TestAccAzureRMPublicIpStatic_basic
--- PASS: TestAccAzureRMPublicIpStatic_basic (83.19s)
PASS
ok  	github.com/terraform-providers/terraform-provider-azurerm/azurerm	83.219s
```