`azurerm_virtual_hub_ip` - Make `public_ip_address_id` required for new instance and ForceNew (#14438)
When fixing tests in PR #14408 I didn't realise/include the changes due to GA in the resource itself, only in the tests:

  Make public_ip_address_id required for new instance as stated here by throwing an error on create, but keep the option Optional to keep it backward compatible
  Make public_ip_address_id ForceNew:
If you have an Azure Route Server created before September 1st and it doesn't have a public IP address asssociated, you'll need to recreate the Route Server so it can obtain an IP address for management purpose.
Error: Code="RouteServerPublicIpAddressCannotBeUpdated" Message="Route Server public ip address cannot be changed. This is not supported.
  Document that this resource is documented as Route Server