`azurerm_databricks_workspace` - Swap the order of PATCH (for tags) and PUT during `Update()`
The `PATCH` request for the workspace can only update the `tags`. The difference between updating it via `PUT` is that the `PATCH` will also update the `tags` of the resources managed by this workspace, including disk encryption set. Most these resources don't need additional permission to update the `tags`, including the disk encryption set, even with CMK enabled.

The exception is that when `managed_disk_cmk_rotation_to_latest_version_enabled` is enabled, the update of the disk encryption set will access to the key vault key during the update of the `tags` (probably because it needs to find the latest version of the key, for validation/retrieving the latest tag). This will then fail a potential user operation that tries to update the `tags` and enable the `managed_disk_cmk_rotation_to_latest_version_enabled` in the same run:

>        Error: updating Workspace (Subscription: "****"
>        Resource Group Name: "****"
>        Workspace Name: "****") Tags: performing Update: unexpected status 400 (400 Bad Request) with error: ApplicationUpdateFail: Failed to update application: '****', because patch resource group failure.

The proper sequence for the above would be:

- PUT the workspace to update properties, including `managed_disk_cmk_rotation_to_latest_version_enabled`. This will then expose the `managed_disk_identity`.
- Assign a proper data plane role (e.g. "Key Vault Crypto Service Encryption User") or access policy to the returned `managed_disk_identity.0.principal_id`, which is the identity that will be used to access the CMK when patching the tags
- PATCH the workspace's tags

The current implementation of `Update()` has the `PUT` then `PATCH` (if changed) sequence, which doesn't give user a chance to do the role assignment in between. The user has to separate the update task into two steps.

This PR changes the order to be `PATCH` (if changed) then `PUT`. In this way, assuming the `managed_disk_cmk_rotation_to_latest_version_enabled` is disabled, the `PATCH` doesn't require additional data plane permissions to updating the tags. After the `Update()`, the user is expected to assign the role to the newly populated `managed_disk_identity`, so that they can continue managing the resources without a problem.