FIX: r/azurerm_eventgrid_event_subscription - limitation less than AZURE (50 char) (#10583)
Fix to address the bug described here: #10545
Small change in validation -> from 50 to 64 characters.

Tested with
azurerm_eventgrid_event_subscription
and
azurerm_eventgrid_system_topic_event_subscription

both can support up to 64 characters in name now.

For len 64+ error message bellow will be shown:

Error: invalid value for name (EventGrid subscription name must be 3 - 64 characters long, contain only letters, numbers and hyphens.)
on main.tf line 60, in resource "azurerm_eventgrid_event_subscription" "default":
60: resource "azurerm_eventgrid_event_subscription" "default" {

Error: invalid value for name (EventGrid subscription name must be 3 - 64 characters long, contain only letters, numbers and hyphens.)
on main.tf line 70, in resource "azurerm_eventgrid_system_topic_event_subscription" "example":
70: resource "azurerm_eventgrid_system_topic_event_subscription" "example" {