Ensuring the `https_only` field is set. Fixes:
```
------- Stdout: -------
=== RUN   TestAccAzureRMFunctionApp_importTags
--- FAIL: TestAccAzureRMFunctionApp_importTags (120.47s)
    testing.go:513: Step 1 error: ImportStateVerify attributes not equivalent. Difference is shown below. Top is actual, bottom is expected.

        (map[string]string) {
        }

        (map[string]string) (len=1) {
         (string) (len=10) "https_only": (string) (len=5) "false"
        }

FAIL
```