docs: *_virtual_machine: add note about provision_vm_agent
Following error happens when `provision_vm_agent` is `false` but
`allow_extension_operations` is `true` (which is the default):

  Error: `allow_extension_operations` cannot be set to `true` when `provision_vm_agent` is set to `false`
  with azurerm_linux_virtual_machine.vm

Setting `allow_extension_operations` to `false` fixes the error.

Test: manual