FIX: r/frontdoor_firewall_policy - Restriction on number of match_condition elements (#10659)
Fix for: #10634

Based on this:
https://github.com/MicrosoftDocs/azure-docs/blob/master/includes/front-door-limits.md

match_condition can support only up to 10 items
Verified in Azure it can support only up to 10 items – not more.
Otherwise error:
Error: creating Front Door Firewall Policy "examplefdwafpolicy" (Resource Group "example-rg"): frontdoor.PoliciesClient#CreateOrUpdate: Failure sending request: StatusCode=0 -- Original Error: Code="BadRequest" Message="WebApplicationFirewallPolicy validation failed. More information "Rule Rule1 exceeds 10 match conditions"."
Because of that I reduced limit from 100 to 10 for match_condition

match_values can support up to 600 items
Verified in Azure it can support up to 600 items for IP Addresses. (operator= "IPMatch")
Otherwise error:
Error: creating Front Door Firewall Policy "examplefdwafpolicy" (Resource Group "example-rg"): frontdoor.PoliciesClient#CreateOrUpdate: Failure sending request: StatusCode=0 -- Original Error: Code="BadRequest" Message="WebApplicationFirewallPolicy validation failed. More information "Policy includes a rule which exceeds 600 IPMatch values"."

match_values can support up to 10 items
Verified in Azure it can support up to 10 items for string match values. (operator= "stringOperator")
Otherwise error:
Error: creating Front Door Firewall Policy "examplefdwafpolicy" (Resource Group "example-rg"): frontdoor.PoliciesClient#CreateOrUpdate: Failure sending request: StatusCode=0 -- Original Error: Code="BadRequest" Message="WebApplicationFirewallPolicy validation failed. More information "Match condition in Rule1 rule has more than 10 match values."."

Because of that I increased limit from 100 to 600 for match_values

Match string value can be up to 256 characters.
Verified in Azure - it can support up to 256 characters in string items
Otherwise error:
Error: creating Front Door Firewall Policy "examplefdwafpolicy" (Resource Group "example-rg"): frontdoor.PoliciesClient#CreateOrUpdate: Failure sending request: StatusCode=0 -- Original Error: Code="BadRequest" Message="WebApplicationFirewallPolicy validation failed. More information "Match condition in Rule1 rule has match value with more than 256 characters"."

I changed documentation and also changed the example name which was not valid for this resource.

More comments:
Ideally this requires conditional validation.
For case IPMatch it can support up to 600 items. This is total number across of all match_values in all match_condition in the one policy
For case string operation it can support up to 10 items only. This is number in match_values only so total number can be higher across of all match_values in all match_condition in the one policy.
Not sure about what is the total number if mixing IPMatch and string types in multiple match_condition blocks.

Do we have any example where we use such sophisticated conditional validator? Any guidance for this?

This initial implementation of fix is conceptually the same as original implementation. It is just limiting to the highest number, lower limits will be handled by Azure as before.