azurerm_service_fabric_cluster - support for Client Certificate… (#6097)
Addressing #4528

Added support in azurerm_service_fabric_cluster for client_certificate_common_name block. Example block:

client_certificate_common_name {
  certificate_common_name = "CertificateCommonName"
  is_admin   = true
  certificate_issuer_thumbprint = "3341DB6CF2AF72C611DF3BE3721A653AF1D43ECD50F584F828793DBE9103C3EE"
}
Change also required updating unit tests for Cluster Code Version (previous was no longer supported) as well as updating thumbprints from "33:41:DB:6C:F2:AF:72:C6:11:DF:3B:E3:72:1A:65:3A:F1:D4:3E:CD:50:F5:84:F8:28:79:3D:BE:91:03:C3:EE"
to
"3341DB6CF2AF72C611DF3BE3721A653AF1D43ECD50F584F828793DBE9103C3EE"
to fix error of

Error: Error creating Service Fabric Cluster "acctest-200312100109887030" (Resource Group "acctestRG-200312100109887030"): servicefabric.ClustersClient#Create: Failure sending request: StatusCode=400 -- Original Error: Code="InvalidCertificateThumbprint" Message="Certificate thumbprint '33:41:DB:6C:F2:AF:72:C6:11:DF:3B:E3:72:1A:65:3A:F1:D4:3E:CD:50:F5:84:F8:28:79:3D:BE:91:03:C3:EE' is invalid." Details=[]