catch up with the team. (#1)
* Adding azure app insights resource

* Fixing the Container Service tests

* Importing from the main repo

* adding vendor dependencies and minor changes

* adding vendor dependencies and minor changes

* Adding in the DocumentDB SDK

* Importing the CosmosDB resource from the main repo

* Porting over the website

* Add VS Code folder to git ignore list;
Fix a few things in README.

* Fixing the formatting

* Include everything under .vscode in gitignore.

* Locking on the NSG name

* Add diff supress func to endpoint_location.

Signed-off-by: stack72 <public@paulstack.co.uk>

* Update acceptance tests.

Signed-off-by: stack72 <public@paulstack.co.uk>

* Create CHANGELOG.md

* Adding more tests for CosmosDB

* Updating the delete

* Update CHANGELOG.md

* max_interval_in_seconds / max_staleness_prefix can be Optional/Computed

* v0.1.0

* Cleanup after v0.1.0 release

* Defaulting the Consistency Level fields

* Renaming to `azurerm_cosmosdb_account`

* Updating the docs

* We should catch missing security group and route table entries for subnets if they're missing from the Azure API response.

* Update CHANGELOG.md

* Sort ResourceID.Path keys for consistent output

While the API may not care what order the key-value path parts are in,
sort the keys so that we can maintain a consistent order for tests and
debugging.

Add more key-values to the test so that it fails more frequently than
not.

* Update CHANGELOG.md

* v0.1.1

* Cleanup after v0.1.1 release

* adding acceptance tests

* making acc tests to pass

* Support import for network interface

make testacc TEST=./azurerm TESTARGS="-run
TestAccAzureRMNetworkInterface_import"
==> Checking that code complies with gofmt requirements...
TF_ACC=1 go test ./azurerm -v -run TestAccAzureRMNetworkInterface_import -timeout 120m
=== RUN   TestAccAzureRMNetworkInterface_importBasic
--- PASS: TestAccAzureRMNetworkInterface_importBasic (117.50s)
=== RUN   TestAccAzureRMNetworkInterface_importIPForwarding
--- PASS: TestAccAzureRMNetworkInterface_importIPForwarding (116.48s)
=== RUN   TestAccAzureRMNetworkInterface_importWithTags
--- PASS: TestAccAzureRMNetworkInterface_importWithTags (126.00s)
=== RUN   TestAccAzureRMNetworkInterface_importMultipleLoadBalancers
--- PASS: TestAccAzureRMNetworkInterface_importMultipleLoadBalancers
(156.05s)
PASS
ok github.com/terraform-providers/terraform-provider-azurerm/azurerm 516.124s

* Fixing the geoReplication tests

* Added Managed Disk as a Data Source

* Updating to include #119

* Fixing the NIC Bug test

* Fixing the broken subnet test

* Fixing the location field to be stored formatted

* Updating to include #113

* Checking for the second item

* Updating to include #122

* Added tags to managed disk doc and sorted data sources alphabetically

* Exposing the FQDN of the master

* Normalize location

Call `azureRMNormalizeLocation` before set to state. There were few
resources missing this.

* Add `MaxItems` to `access_policy`

Reference: https://github.com/Azure/azure-rest-api-specs/blob/05123a9ba41f02c6e8ad24c6737881ba84353e38/arm-keyvault/2015-06-01/swagger/keyvault.json#L353

* Fix `azurerm_key_vault` import

Before

```
make testacc TEST=./azurerm TESTARGS="-run TestAccAzureRMKeyV"
==> Checking that code complies with gofmt requirements...
TF_ACC=1 go test ./azurerm -v -run TestAccAzureRMKeyV -timeout 120m
=== RUN   TestAccAzureRMKeyVault_importBasic
--- FAIL: TestAccAzureRMKeyVault_importBasic (93.35s)
        testing.go:428: Step 1 error: ImportStateVerify attributes not
equivalent. Difference is shown below. Top is actual, bottom is
expected.

                (map[string]string) {
                }

                (map[string]string) (len=7) {
                 (string) (len=15) "access_policy.#": (string) (len=1) "1",
                 (string) (len=33) "access_policy.0.key_permissions.#": (string) (len=1) "1",
                 (string) (len=33) "access_policy.0.key_permissions.0": (string) (len=3) "all",
                 (string) (len=25) "access_policy.0.object_id": (string) (len=36) "0312e94a-ce28-4814-85b6-ec3b587cf2cc",
                 (string) (len=36) "access_policy.0.secret_permissions.#": (string) (len=1) "1",
                 (string) (len=36) "access_policy.0.secret_permissions.0": (string) (len=3) "all",
                 (string) (len=25) "access_policy.0.tenant_id": (string) (len=36) "2d5fc15a-26b1-49b6-a937-4379c05e8ef8"
                }

=== RUN   TestAccAzureRMKeyVault_basic
--- PASS: TestAccAzureRMKeyVault_basic (89.18s)
=== RUN   TestAccAzureRMKeyVault_update
--- PASS: TestAccAzureRMKeyVault_update (117.42s)
FAIL
exit status 1
FAIL github.com/terraform-providers/terraform-provider-azurerm/azurerm 300.066s
make: *** [testacc] Error 1
```

After:

```
make testacc TEST=./azurerm TESTARGS="-run TestAccAzureRMKeyV"
==> Checking that code complies with gofmt requirements...
TF_ACC=1 go test ./azurerm -v -run TestAccAzureRMKeyV -timeout 120m
=== RUN   TestAccAzureRMKeyVault_importBasic
--- PASS: TestAccAzureRMKeyVault_importBasic (91.88s)
=== RUN   TestAccAzureRMKeyVault_basic
--- PASS: TestAccAzureRMKeyVault_basic (93.76s)
=== RUN   TestAccAzureRMKeyVault_update
--- PASS: TestAccAzureRMKeyVault_update (129.03s)
PASS
ok github.com/terraform-providers/terraform-provider-azurerm/azurerm 314.768s
```

* Updating to include #121

* typo

* Updating to include #124

* Fixing up the PR comments

* Added tests covering the `other` application type

* Renaming app_insights -> application_insights

* Adding documentation for Application Insights

* Updating to include #125

* Updating to include #123

* Adding `azurerm_application_insights` from #3

* Fix runtime error on conversion of *string to string when presence of
public ip

Before:

```
$ make testacc TEST=./azurerm TESTARGS="-run
TestAccAzureRMNetworkInterface_importPublicIP"
==> Checking that code complies with gofmt requirements...
TF_ACC=1 go test ./azurerm -v -run
TestAccAzureRMNetworkInterface_importPublicIP -timeout 120m
=== RUN   TestAccAzureRMNetworkInterface_importPublicIP
panic: interface conversion: interface {} is *string, not string

goroutine 393 [running]:
github.com/terraform-providers/terraform-provider-azurerm/azurerm.resourceArmNetworkInterfaceIpConfigurationHash(0x183ad00, 0xc4201aa4b0, 0xc4202a9478)
        /Users/thiagocaiubi/Development/go/src/github.com/terraform-providers/terraform-provider-azurerm/azurerm/resource_arm_network_interface_card.go:401 +0xa75
github.com/terraform-providers/terraform-provider-azurerm/vendor/github.com/hashicorp/terraform/helper/schema.(*Set).hash(0xc4202a9460, 0x183ad00, 0xc4201aa4b0, 0x10, 0x20)
        /Users/thiagocaiubi/Development/go/src/github.com/terraform-providers/terraform-provider-azurerm/vendor/github.com/hashicorp/terraform/helper/schema/set.go:180 +0x3d
github.com/terraform-providers/terraform-provider-azurerm/vendor/github.com/hashicorp/terraform/helper/schema.(*Set).add(0xc4202a9460, 0x183ad00, 0xc4201aa4b0, 0x1884d00, 0x1, 0xc4202a9460)
        /Users/thiagocaiubi/Development/go/src/github.com/terraform-providers/terraform-provider-azurerm/vendor/github.com/hashicorp/terraform/helper/schema/set.go:167 +0x81
github.com/terraform-providers/terraform-provider-azurerm/vendor/github.com/hashicorp/terraform/helper/schema.(*Set).Add(0xc4202a9460, 0x183ad00, 0xc4201aa4b0)
        /Users/thiagocaiubi/Development/go/src/github.com/terraform-providers/terraform-provider-azurerm/vendor/github.com/hashicorp/terraform/helper/schema/set.go:69 +0x44
github.com/terraform-providers/terraform-provider-azurerm/vendor/github.com/hashicorp/terraform/helper/schema.NewSet(0x198c5e8, 0xc4202fac30, 0x1, 0x1, 0xc4202fac00)
        /Users/thiagocaiubi/Development/go/src/github.com/terraform-providers/terraform-provider-azurerm/vendor/github.com/hashicorp/terraform/helper/schema/set.go:56 +0xa2
github.com/terraform-providers/terraform-provider-azurerm/azurerm.resourceArmNetworkInterfaceRead(0xc4201cda40, 0x1875c20, 0xc4202ee000, 0xc4203690e0, 0x0)
```

After:

```
$ make testacc TEST=./azurerm TESTARGS="-run
TestAccAzureRMNetworkInterface_importPublicIP"
==> Checking that code complies with gofmt requirements...
TF_ACC=1 go test ./azurerm -v -run
TestAccAzureRMNetworkInterface_importPublicIP -timeout 120m
=== RUN   TestAccAzureRMNetworkInterface_importPublicIP
--- PASS: TestAccAzureRMNetworkInterface_importPublicIP (120.69s)
PASS
ok github.com/terraform-providers/terraform-provider-azurerm/azurerm 120.801s
```

* Making Name in VMSS Storage_Profile_OS_Disk Optional

* Updated documentation

* Updated check for unmanaged disks and name property

* Updating to include #128

* Fix Changelog Links Script for azurerm provider

* Update Changelog for azurerm provider

* Refactoring the tests

* Allow updating of CDN Endpoints. Fixes #97

* Registering for App Insights if it's not already registered

* Docs covering the inline NSG/NSR resources. Fixes #115

* Adding a disclaimer to Subnets/Virtual Networks

* Reordering the network sidebar

* Fixing the highlighting for Express Route/LNG's

* Updating to include #134

* Updating the ARM Template Deployment docs to add a disclaimer

* Making the Network Security Group Name a ForceNew property

* Updating the documentation

* Updating to include #108

* Updating to include #138

* Updating to include #129

* Fixes #127 Improve docs for delete_os_disk_on_termination

* DNS PTR Reocrd - Initial Work

* DNS PTR Record - Initial PR

* Added import test, updated docs, converted test strings into funcs to conform with newer approach

* Initial support for Redis Backups

* Adding in a state migration covering the redis backup setting

* Making the settings optional / adding tests

* Updating the documentation to include the new settings

* Need to use a Premium SKU to set the field at all

* Removing the state migration

* Adding a test updating the settings

* Switching the backup params to be native types

* Converting the existing fields to proper data types

* Parsing values directly out of the schema if they're present

Updating the validation to use the Enum's

* Converting the tests to use the functions

* Updating the documentation to match

* Added a test for the backup frequency

* Copy/Paste fail

* Formatting

* Adding a primary/secondary blob connection string

* Updating to include #130

* Refactoring the existing tests to use functions

* Added a test covering the blob connection string

* Updating to include #142

* v0.1.2

* Cleanup after v0.1.2 release

* Simplifying the GNUMakefile

* Made changes suggested for the PR

* Added tag validation to tests

* Adding back the GNUmakefile test-compile step

* Cleaning up some unnecessary code

* Adding in etags / updating the casing of ttl

* Add delete comments to other examples

* Move managed disk example to top

* Combine unmanaged disk examples

* Make comments consistent

* Fix azure table storage name length requirement.

https://docs.microsoft.com/en-us/rest/api/storageservices/Understanding-the-Table-Service-Data-Model?redirectedfrom=MSDN#table-names.

* Super minor docfix: 'or' -> 'of'.

* Updating `//` -> `#` to match the convention

* Updating to include #141

* Better documenting the CDN endpoints. Fixes #56

* Add some boundary tests around storage table name length requirements.

* Updating to include #143

* Remove must be PEM format string

* Making it possible to create a Linux VM without a password. Fixes #152

* Making admin_password a sensitive field

* New Resource: `azurerm_servicebus_queue` (#151)

* Importing the work from hashicorp/terraform#14631 by @iljaskevic

* Refactoring the tests

* Formatting

* Importing the docs

* Refactoring

* Making `duplicate_detection_history_time_window` computed

* Refactoring the tests

* Fixing the formatting

* Updating to include #151

* Updating to include #154

* Cleaning up service bus namespaces

* Service Bus Topic's can be disabled

* Refactoring

* Actually enabling disabled

* Adding the new field to the docs

* Switching to use the azure wrappers

* Updating to include #150

* Readme: Fix wrong logo URL (#155)

* examples: Migrating examples from hashicorp/terraform repository (#163)