Removing the `AzurePublicPeering` tests since this feature is no longer available on new connections.
Fixes:

```
------- Stdout: -------
=== RUN   TestAccAzureRMExpressRouteCircuit
=== RUN   TestAccAzureRMExpressRouteCircuit/basic
=== RUN   TestAccAzureRMExpressRouteCircuit/basic/metered
=== RUN   TestAccAzureRMExpressRouteCircuit/basic/unlimited
=== RUN   TestAccAzureRMExpressRouteCircuit/basic/update
=== RUN   TestAccAzureRMExpressRouteCircuit/PrivatePeering
=== RUN   TestAccAzureRMExpressRouteCircuit/PrivatePeering/azurePrivatePeering
=== RUN   TestAccAzureRMExpressRouteCircuit/PrivatePeering/importPrivatePeering
=== RUN   TestAccAzureRMExpressRouteCircuit/PublicPeering
=== RUN   TestAccAzureRMExpressRouteCircuit/PublicPeering/azurePublicPeering
=== RUN   TestAccAzureRMExpressRouteCircuit/PublicPeering/importPublicPeering
=== RUN   TestAccAzureRMExpressRouteCircuit/MicrosoftPeering
=== RUN   TestAccAzureRMExpressRouteCircuit/MicrosoftPeering/microsoftPeering
=== RUN   TestAccAzureRMExpressRouteCircuit/MicrosoftPeering/importMicrosoftPeering
=== RUN   TestAccAzureRMExpressRouteCircuit/authorization
=== RUN   TestAccAzureRMExpressRouteCircuit/authorization/multiple
=== RUN   TestAccAzureRMExpressRouteCircuit/authorization/import
=== RUN   TestAccAzureRMExpressRouteCircuit/authorization/basic
=== RUN   TestAccAzureRMExpressRouteCircuit/authorizationImport
=== RUN   TestAccAzureRMExpressRouteCircuit/authorizationImport/basic
=== RUN   TestAccAzureRMExpressRouteCircuit/circuitImport
=== RUN   TestAccAzureRMExpressRouteCircuit/circuitImport/unlimited
=== RUN   TestAccAzureRMExpressRouteCircuit/circuitImport/metered
--- FAIL: TestAccAzureRMExpressRouteCircuit (3726.39s)
    --- PASS: TestAccAzureRMExpressRouteCircuit/basic (474.49s)
        --- PASS: TestAccAzureRMExpressRouteCircuit/basic/metered (141.26s)
        --- PASS: TestAccAzureRMExpressRouteCircuit/basic/unlimited (164.34s)
        --- PASS: TestAccAzureRMExpressRouteCircuit/basic/update (168.89s)
    --- PASS: TestAccAzureRMExpressRouteCircuit/PrivatePeering (528.77s)
        --- PASS: TestAccAzureRMExpressRouteCircuit/PrivatePeering/azurePrivatePeering (261.39s)
        --- PASS: TestAccAzureRMExpressRouteCircuit/PrivatePeering/importPrivatePeering (267.38s)
    --- FAIL: TestAccAzureRMExpressRouteCircuit/PublicPeering (374.02s)
        --- FAIL: TestAccAzureRMExpressRouteCircuit/PublicPeering/azurePublicPeering (187.78s)
            testing.go:513: Step 0 error: Error applying: 1 error(s) occurred:

                * azurerm_express_route_circuit_peering.test: 1 error(s) occurred:

                * azurerm_express_route_circuit_peering.test: Long running operation terminated with status 'Failed': Code="InvalidBgpPeerType" Message="Public peering has been deprecated" Details=[]
        --- FAIL: TestAccAzureRMExpressRouteCircuit/PublicPeering/importPublicPeering (186.24s)
            testing.go:513: Step 0 error: Error applying: 1 error(s) occurred:

                * azurerm_express_route_circuit_peering.test: 1 error(s) occurred:

                * azurerm_express_route_circuit_peering.test: Long running operation terminated with status 'Failed': Code="InvalidBgpPeerType" Message="Public peering has been deprecated" Details=[]
    --- PASS: TestAccAzureRMExpressRouteCircuit/MicrosoftPeering (1296.32s)
        --- PASS: TestAccAzureRMExpressRouteCircuit/MicrosoftPeering/microsoftPeering (773.43s)
        --- PASS: TestAccAzureRMExpressRouteCircuit/MicrosoftPeering/importMicrosoftPeering (522.89s)
    --- PASS: TestAccAzureRMExpressRouteCircuit/authorization (558.47s)
        --- PASS: TestAccAzureRMExpressRouteCircuit/authorization/multiple (199.21s)
        --- PASS: TestAccAzureRMExpressRouteCircuit/authorization/import (163.76s)
        --- PASS: TestAccAzureRMExpressRouteCircuit/authorization/basic (195.49s)
    --- PASS: TestAccAzureRMExpressRouteCircuit/authorizationImport (205.73s)
        --- PASS: TestAccAzureRMExpressRouteCircuit/authorizationImport/basic (205.73s)
    --- PASS: TestAccAzureRMExpressRouteCircuit/circuitImport (288.60s)
        --- PASS: TestAccAzureRMExpressRouteCircuit/circuitImport/unlimited (139.41s)
        --- PASS: TestAccAzureRMExpressRouteCircuit/circuitImport/metered (149.19s)
FAIL
```